apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: 
nodes:     # we can always modify this conf file according to our need.
- role: control-plane
  image: kindest/node:v1.31.1
- role: worker
  image: kindest/node:v1.31.1
- role: worker
  image: kindest/node:v1.31.1
- role: worker
  image: kindest/node:v1.31.1
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
